server:
  port: 8500

spring:
  application:
    name: eureka-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  server:
    eviction-interval-timer-in-ms: 9000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}